name: GitHub Action

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      uses: MrRamych/gradle-actions/openjdk-13@3.1
      with:
        args: build
    - name: Cache
      uses: actions/cache@v1.1.0
      with:
        path: ~/.gradle.caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
