name: main

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        chmod +x ./gradlew
        ./gradlew build
    - name: Cache
      uses: actions/cache@v1.1.0
      with:
        path: ~/.gradle.caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
